---
apiVersion: v1
kind: Secret
metadata:
  name: DNDIndia-wind-turbine-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-demo/DNDIndia-wind-turbine-gitops
